[package]
name = "threadpools"
version = "1.1.0"
edition = "2024"
license = "MIT"
description = "Efficient, configurable, zero-dependency thread pool implementations. Flexible and usable for a wide variety of applications."

[dependencies]
